[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.28"


[workspace]
members = ["programs/cp-swap"]

[features]
seeds = false
skip-lint = false

[programs.Localnet]
raydium_cp_swap = "3aP5TZpYW5Wdjf4KwM2rR2KffgaS5e4wQrxsroMW1j4u"


[registry]
url = "https://github.com/raydium-io/raydium-cp-swap"

[provider]
cluster = "Localnet"
wallet = "~/.config/openos/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.test.ts"

[test]
startup_wait = 10000

[test.validator]
url = "https://api.mainnet.openverse.network"

[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8" # pool fee receiver

[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2" # index 0 AMM Config account
